### ISSUE TITLE
output to a separate file or via unix socket

### ISSUE THREAD

**Issue by MingchunZhao** [2ndQuadrant/pgaudit#10]
Would you have any plan to support some output interfaces like file,socket,pipe other than pg_log?

**Comment by jonranes** [comment]
After trying a few different ways to deal with the output of this contrib module I have found the best solution is to send it to Graylog on the same server through 127.0.0.1.  Your Graylog server can then forward the events to your main Graylog wherever that is.

I have forked the repository with a working example using libcurl.

https://github.com/jonranes/pgaudit

to install on centos 6.5
https://github.com/jonranes/pgaudit/wiki

**Comment by amenonsen** [comment]
I'm closing this issue preparatory to dropping this repository in favour of the pgaudit/pgaudit repository.
