### ISSUE TITLE
Could not load library Error

### ISSUE THREAD

**Issue by alancfloyd** [2ndQuadrant/pgaudit#11]
I have built postgres 9.5 and then built pgadmin with MinGW on windows 7 per the instuctions on this site. Then copied the 3 files: pgaudit to C:\Program Files\PostgreSQL\9.5\lib and pgaudit.control and pgaudit--1.0.sql to C:\Program Files\PostgreSQL\9.5\share\extension on an already existing windows install of postgres 9.5.

When I run CREATE EXTENSION pgaudit; in the query window of pgadmin, I get the following error.

ERROR:  could not load library "C:/Program Files/PostgreSQL/9.5/lib/pgaudit.dll": %1 is not a valid Win32 application.

Any idea what is wrong?

**Comment by amenonsen** [comment]
I'm closing this issue preparatory to dropping this repository in favour of the pgaudit/pgaudit repository.
