### ISSUE TITLE
CentOS 6.6: /usr/pgsql-9.4/lib/pgaudit.so: undefined symbol: bms_next_member

### ISSUE THREAD

**Issue by dup2** [2ndQuadrant/pgaudit#3]
When building against 9.4 on a CentOS 6.6 box with the packages from PGDG, the server startup fails with a undefined symbol error. 

Packages installed:

    postgresql94.x86_64   9.4.0-1PGDG.rhel6 @pgdg94 
    postgresql94-contrib.x86_64
    postgresql94-devel.x86_64
    postgresql94-libs.x86_64
    postgresql94-server.x86_64

Building:

    [root@vagrant-centos66 pgaudit]# PATH=$PATH:/usr/pgsql-9.4/bin/ make USE_PGXS=1
    gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fpic -I. -I./ -I/usr/pgsql-9.4/include/server -I/usr/pgsql-9.4/include/internal -I/usr/include/et -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o pgaudit.o pgaudit.c
    gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -I/usr/include/et -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fpic -shared -o pgaudit.so pgaudit.o -L/usr/pgsql-9.4/lib -L/usr/lib64 -Wl,--as-needed

Configuration:

    shared_preload_libraries = 'pg_stat_statements, auto_explain,pgaudit'

While compiling works, after installing by copying the files to /usr/pgsql-9.4/lib and starting the server we get this undefined symbol error:

    2015-01-12 10:23:53 UTC FATAL:  could not load library "/usr/pgsql-9.4/lib/pgaudit.so": /usr/pgsql-9.4/lib/pgaudit.so: undefined symbol: bms_next_member

Does it not work at all against a vanilla 9.4 installation?

**Comment by amenonsen** [comment]
Hi.

Thanks for letting us know. It's meant to work against 9.4, but a recent change inadvertently broke it by using a function that was added later. I'll fix it and commit shortly.

-- Abhijit

**Comment by dup2** [comment]
Hi @amenonsen, thanks for your reply. Did you already get a chance to look into this? Shall we use a older version? How can I help fixing this?

Cheers

**Comment by amenonsen** [comment]
Hi.

I did look at it, and it turned out to not be as easy as I thought to fix it. I could use bms_first_member, but that destructively modifies the bitmapset in question, which I can't do. So I would have to copy the bitmapsets first, or I could copy bms_next_member from the 9.5 source into the module, but that needs quite a bit more of copy and paste than I had hoped.

I'm in the middle of some other changes to pgaudit, so I'll fix this too. Sorry it's taking longer than I had hoped.

**Comment by amenonsen** [comment]
Try it now and let me know if it works?

**Comment by dup2** [comment]
Much better! Startup worked, we get audit log events and will now try to configure it for our needs - Thanks!
