### ISSUE TITLE
audit log entries with sensible data

### ISSUE THREAD

**Issue by walpino** [2ndQuadrant/pgaudit#7]
Hi 

I just managed to audit some users 

I saw in the audit entries that pgaudit some sensible data too.

...LOG:  AUDIT,2015-03-19 14:35:34.963482+01,database1,user1,user1,USER,ALTER ROLE,,,alter user user1 with password 'xyz';

It is correct that the entry is in the log file, but I would suggest to clear the password if it is possible

You know what I mean?

Thanks

**Comment by amenonsen** [comment]
I'm closing this issue preparatory to dropping this repository in favour of the pgaudit/pgaudit repository.
