### ISSUE TITLE
understanding `effective user`

### ISSUE THREAD

**Issue by brancz** [2ndQuadrant/pgaudit#8]
First of all, thank you for your effort, this is something PostgreSQL desperately needs from my perspective.

From the documentation I do not entirely understand what `effective user` is. What I would hope for, is that I can hand a user from my Application using the database to Identify which user in my System caused the statement to execute. Furthermore it would be neat, if the statement contained a program or action that the user executed which in turn caused the SQL statement to be executed.

Is my assumption correct or would it be possible to implement such a feature if not already present?

**Comment by nineinchnick** [comment]
I believe it's the current role if you'd use `SET ROLE` to change it after connecting to the server.

I'm using [audit-trigger](http://github.com/2ndQuadrant/audit-trigger), which I extended to store application metadata like you describe by setting custom session variables in my application and reading them in the trigger.

This is custom application specific behavior and you'd probably have to fork this extension to add it yourself.

**Comment by amenonsen** [comment]
I'm closing this issue preparatory to dropping this repository in favour of the pgaudit/pgaudit repository.
